version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
    ports:
      - "5001:5000"
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
